insert into movies (title, genre, release_year) values ('Harry Potter and the Deathly Hallows: Part 2', 'ADVENTURE', 2011);
insert into movies (title, genre, release_year) values ('Argo', 'THRILLER', 2012);
insert into movies (title, genre, release_year) values ('12 Years a Slave', 'DRAMA', 2013);
insert into movies (title, genre, release_year) values ('Selma', 'DRAMA', 2014);
insert into movies (title, genre, release_year) values ('Mad Max: Fury Road', 'ADVENTURE', 2015);
insert into movies (title, genre, release_year) values ('Moonlight', 'DRAMA', 2016);
insert into movies (title, genre, release_year) values ('Lady Bird', 'COMEDY', 2017);
insert into movies (title, genre, release_year) values ('Black Panther', 'ADVENTURE', 2018);
insert into movies (title, genre, release_year) values ('Parasite', 'COMEDY', 2019);
insert into movies (title, genre, release_year) values ('Portrait of a Lady on Fire', 'ROMANTIC', 2020);